name: build

on:
  push:
    branches:
      - "master"
    paths:
      - 'src/**'
      - '.github/**'
      - 'pom.xml'
  pull_request:
    branches:
      - "master"
    paths:
      - 'src/**'
      - '.github/**'
      - 'pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file pom.xml